### ISSUE TITLE
Only "Calendar" map works

### ISSUE THREAD

**Issue by reiser4** [zoffline/zwift-offline#107]
Hello, I am trying this awesome project. I can ride successfully in Calendar map, but when I chose a different map I see this error 400:

![image](https://user-images.githubusercontent.com/2445517/102101152-8e302300-3e2a-11eb-8f66-3712936f9a11.png)

how can I get more debug information? thanks!

**Comment by rocknt** [comment]
A have the same problem

**Comment by reiser4** [comment]
I tried by cloning the repo and running it manually. It works! The login screen is a bit different and lets me choose the profile.

**Comment by oldnapalm** [comment]
I can't reproduce this error.

Could you try to run from source using this fork? (the exe release you tried was built from it) https://github.com/oldnapalm/zwift-offline

This exe was built from the main repo, please try it if you can
[zoffline_1.0.59353.zip](https://github.com/zoffline/zwift-offline/files/5690880/zoffline_1.0.59353.zip)

**Comment by oldnapalm** [comment]
Found the issue, it was caused by the missing remember_token cookie which is created only if you enable multiplayer and login. Thanks Yosh from the Discord channel for the help.

Updated the releases.

In the main repo it's the single player with multi profile
https://github.com/zoffline/zwift-offline/releases/tag/zoffline_1.0.59353

In my fork it's the multiplayer (or single player with single profile)
https://github.com/oldnapalm/zwift-offline/releases/tag/zoffline_1.0.59353
