### ISSUE TITLE
Weird error

### ISSUE THREAD

**Issue by tsofron** [zoffline/zwift-offline#116]
Hey guys,
first - thanks for this workaround ;-)
Second - since today I'm experiencing the following error when launching zoffline:
![image](https://user-images.githubusercontent.com/72147998/110683601-e0dc6980-81e4-11eb-90db-4f310718f696.png)

Can you please help? Besides some windows updates, nothing else changed...
Thanks!

**Comment by tsofron** [comment]
Ok - it's VMWare that's causing the issue :(...Out of curiosity - any workaround for this (besides uninstalling VMWare)?

**Comment by zoffline** [comment]
I *think* you can modify VMWare Workstation to bind to different ports instead of 80/443 (assuming that's your issue). You could also terminate the VMWare service binding to those ports just while running zoffline and then restart the service after.

Alternatively, you can run zoffline in a VM, on another machine, or in a Docker container (without mapping the ports to the host). For all of those you'll need to add a server-ip.txt file in the storage directory containing the IP of the machine zoffline is running on.
