### ISSUE TITLE
Adding random bot runners to not feel alone while running

### ISSUE THREAD

**Issue by Jayknightfr** [zoffline/zwift-offline#167]
I love this server, it's fantastic. But i feel a bit lonely. In the online Zwift it's fun to have random strangers running or riding all around and seeing their name and flags.
Is there a way to add bots so that it feels a bit more alive?

**Comment by oldnapalm** [comment]
There is a way to load your previous activities as bots but it's not simple, it was explained in #146.

About "random" bots, I would say it's not impossible, but very difficult because the rider/runner position and speed are calculated by the client, we can't do it server side without all the simulation parameters.

**Comment by Jayknightfr** [comment]
Oh okay, i thought everything was done server side and adding bots would be easier.

I checked #146 and i might play with that ghost tool.
Maybe i could suggest adding the option to have some community ghost files in the repo for people to download? I guess if we all share some of our ghosts, it could be interesting. Or maybe even have the ofline server upload some ghosts?

**Comment by oldnapalm** [comment]
The idea of sharing ghosts (or bots) is good, but it would need a server to host the files, we can't just allow everyone to upload files to the github repo.
