### ISSUE TITLE
K8S like setup? 

### ISSUE THREAD

**Issue by OleksiiPasihnyk** [zoffline/zwift-offline#205]
Good time of the day Team. 
I was really watching you project for a while - it is fascinating! 
But in our parts of the world it was warm enough that I did not bothered to launch it for myself) 
Now with the temperatures getting colder and way more rain, I've started wondering is it possible to launch zoffline in k8s environment? 
I can consider myself mid tier DevOps guy who works with K8s on the daily basis and definitely would love to try, as well as dedicate a small piece of x86 hardware for that potentially core i5 +16Gb of Ram + ~500gb of ssd. 
Would appreciate for any starting inputs - 
- Linux Image
- link to tutorial what is required
- any additioanl k8s settings required
etc. 
want to do it on the local cluster, not in eks or anything. means a lot of fun ahead

**Comment by daktak** [comment]
I run this on bare metal, as I can just do a git pull and be up to date.
Otherwise you'd have to rebuild and package into a docker image. You would also have to right a helm chart to install. You would probably need to write a start up script to populate the configuration, maybe from environment variables or k8 secrets.
I'm sure it would be doable, but I wouldn't consider K8S giving any benefit.
I run server and client (using lutris/wine) on Fedora35 on a T440p.

**Comment by OleksiiPasichnyk** [comment]
My intent is to actually make it more complicated than needed) As I'm still cycling outside ( weather permitting) but want to have some "pet" project to have fun with. 
I would imagine that having "baked" image with all dependencies is more stable that following readmi and having fun with python versions. It is just me - I know it is 70% failure chance at the moment( I simply run out of time).
 but I'm still investigating, for now.

So far defined steps
Hardware 
( what currently exist)
1.  physical node core i5 + 16Gb RAM + 500 gb SSD - 1Gb Ethernet
2. physical node q9640 + 8 Gb RAM + 500 Gb SSD - 1Gb Ethrnet
(what currently does not exist but might be needed)
1. HW for the firewall toutging the idea of the [link](https://shop.zimaboard.com/en-ca/products/zimaboard-single-board-server-for-creators-8g-32gb-linux-windows-openwrt-pfsense-andorid-libreelec-development-board-low-cost-hackable-single-board-server)
2. Any additional inputs?
Software
1. Need proper VM machines managments/emulation tool of the local cloud ( potentially Proxmox) 
4. Local firewall ( TBD)
5. Proper LB and potentially HA config for the k8s ( 3 nodes with routing etc.) ( have a great example on how to do it with k3s)
6. Install and configure k8s in HA config
7. Have image build tool setup and configured ( TBD, not sure yet)
8. Bake image 
9. Run it and have other fun(troiubleshoot) with a networking

Please confirm that it is ok to keep track of this in here? 
Or should I create a fork or something? because it is an infra setup, not a zoffline itself.

**Comment by oldnapalm** [comment]
I don't have experience with this stuff, but I think if you want to use load balancing you will need some modifications in zoffline, because for now it assumes there will be only one TCP and one UDP server, and both will have the same IP address.

See https://github.com/zoffline/zwift-offline/blob/167cf21d03d1d7e9cd50070d6e01843679ae19f7/standalone.py#L258

Also, standalone.py (which handles HTTP, TCP and UDP) would need to work independently (communicate over network) of zwift_offline.py (which handles HTTPS), for now they need to be run on the same machine to be able to communicate.

**Comment by daktak** [comment]
On a related note, I found a zwift-client container
https://github.com/netbrain/zwift

**Comment by divfor** [comment]
zoffline is a very light-level server so docker-compose is enough, why k8s? do you want to scale it up to support thousands of zwift clients concurrently?
in the case of k8s, docker-compose file is clear good for it. you need to build/pull container image (k8s does not make it for you), make a deployment/pod yaml file (based on the docker-compose file), and create a yaml file to describe a k8s NodePort service (will map given ports). that is all.

**Comment by OleksiiPasihnyk** [comment]
I'm devops which like to poke on things. Also avid bicyclist. 

And I was(still) having fun with building on prem k3s cluster on 2 laptop nodes for myself. 
setup is done. now figuring parts of VPC such as LB + storage solution for myself. and might be running it all through my domain name. 

Yes I want to simulate production like env. and it is a looong way to go for a 1 person. 

I'm still set to do so. 
I use zofline just as a case study scenario, because interest to launch it properly keeps me driving forward. 

Simple as that and I'm following project as a cyclist but I'm cycling outdoor these days mostly, it is warm enough in raincouver and no space for the proper setup... unfortunately yet. 
I will keep.you guys posted how it went. 
rebuilding the image is a least of my worries) 
not looking for scale, not looking for 1000s of users. would be happy to finish it just for me alone) 
I will definitely share my journey here once I get to the config setup, so you can throw stone or two on the graveyard of my project)
