### ISSUE TITLE
Can we link Zwift_ver_cur.xml and ZwiftMac_ver_cur.xml file to under zwift:storage/

### ISSUE THREAD

**Issue by divfor** [zoffline/zwift-offline#223]
as the official zwift client is keeping updating, we need to put its new Zwift_ver_cur.xml and ZwiftMac_ver_cur.xml files to directory inside the docker container. 
I make a workaround to copy them to running container manually:

```bash
for i in ZwiftMac_ver_cur.xml Zwift_ver_cur.xml; do
  j=/usr/src/app/zwift-offline/cdn/gameassets/Zwift_Updates_Root/$i
  md5h=$(md5sum ./$i | awk '{print $1}')
  echo "$md5h: $i"
  md5c=$(docker exec zoffline md5sum $j | awk '{print $1}')
  echo "$md5c: zoffline:$j"
  docker cp $i zoffline:$j
done
```

can we link them to up-to-date files under volume 'storage'?

**Comment by oldnapalm** [comment]
I can't answer your question but will add a comment/suggestion.

Notice that just updating the ver_cur files doesn't ensure that the latest Zwift client will work properly with zoffline. Look at the last update for example, changes to variants.txt were needed to enable the holo replay for routes and zwift_offline.py had to be updated to have them working at all (even for segments) due to changes in the request URL.

But if you just want to have the latest ver_cur files, you can change the container DNS server (add in docker-compose.yaml)
```
         dns:
            - 8.8.8.8
```
then change this line to just `if self.path.startswith('/gameassets/'):`
https://github.com/zoffline/zwift-offline/blob/3f21baa20c741954846f075c414f525b6040415b/standalone.py#L122

**Comment by oldnapalm** [comment]
As of https://github.com/zoffline/zwift-offline/commit/1a0650a97da745804f78a36a9aea5af24ec66e18 you don't need to change the container DNS server, just remove `and not path_end in exceptions`.

**Comment by divfor** [comment]
I use a NUC pc box to run zoffline in standalone mode. it also runs a dnsmasq DNS server for wireguard to map zwift.com to localhost. so I need to figure out other way if I use the above code change.

**Comment by oldnapalm** [comment]
I think it would still work. The dnspython server will be used only to resolve hostnames when the server will proxy gameassets. The dnsmasq server will still resolve zwift.com to localhost (don't change the container dns, just remove the exceptions so that ver_cur files will also be obtained from official Zwift server).

**Comment by oldnapalm** [comment]
If you want to link the files to the host filesystem I think it's better to add another volume with the directory containing the files
```
        volumes:
           - ./storage/:/usr/src/app/zwift-offline/storage
           - ./cdn/gameassets/Zwift_Updates_Root/:/usr/src/app/zwift-offline/cdn/gameassets/Zwift_Updates_Root
```
Although mounting single files should work too
```
        volumes:
           - ./storage/:/usr/src/app/zwift-offline/storage
           - ./storage/Zwift_ver_cur.xml:/usr/src/app/zwift-offline/cdn/gameassets/Zwift_Updates_Root/Zwift_ver_cur.xml
           - ./storage/ZwiftMac_ver_cur.xml:/usr/src/app/zwift-offline/cdn/gameassets/Zwift_Updates_Root/ZwiftMac_ver_cur.xml
```

https://stackoverflow.com/questions/42248198/how-to-mount-a-single-file-in-a-volume

**Comment by divfor** [comment]
I tried below and it works. mount new folder with 4 files totally:
```bash
# ls -l
total 12
-rw-r--r--  1 root root  436 2月  22 14:36 docker-compose.yml
drwxr-xr-x 10 root root 4096 2月  22 14:44 storage
drwxr-xr-x  2 root root 4096 2月  22 14:38 Zwift_Updates_Root

# ls -l Zwift_Updates_Root/
total 16
-rw-r--r-- 1 root root  73 12月 16 07:39 LauncherMac_ver_cur.xml
-rw-r--r-- 1 root root  53 12月 16 07:39 Launcher_ver_cur.xml
-rw-r--r-- 1 root root 285 2月   7 16:07 ZwiftMac_ver_cur.xml
-rw-r----- 1 root root 282 11月 29 14:38 Zwift_ver_cur.xml
```
docker-compose.yaml:
```yaml
    volumes:
      - ./storage/:/usr/src/app/zwift-offline/storage
      - ./Zwift_Updates_Root/:/usr/src/app/zwift-offline/cdn/gameassets/Zwift_Updates_Root
```
