### ISSUE TITLE
Pace partners / Ghosts not working on android

### ISSUE THREAD

**Issue by mixenSK** [zoffline/zwift-offline#228]
Hello, When I connect to pace partner, it only shows "locating Diesel..." and ghosts don't appear or save either.
[logfile_-1_%5B2023-03-15_11%3A57%3A16%5D.txt.gz](https://github.com/zoffline/zwift-offline/files/10978924/logfile_-1_.5B2023-03-15_11.3A57.3A16.5D.txt.gz)

**Comment by oldnapalm** [comment]
Hello. Since you are (supposedly) not running zoffline on the same device that Zwift is running, you need to create a `server-ip.txt` file in the `storage` directory containing the IP address of the machine running zoffline. Then in your log, where you are seeing `[INFO] TCP host 127.0.0.1:3025 (secure)` you should see the server IP instead.

Are you using the exe release? I noticed this information is not present in the instructions for this option of step 1.

**Comment by mixenSK** [comment]
I created a server-ip.txt file in the storage directory containing the IP address and it works now. THANK YOU!
Yes, I use the nightly zoffline exe.

**Comment by mixenSK** [comment]
Only pace partners works. I did a test ride but the ghost didn't save to the ghosts folder.

**Comment by oldnapalm** [comment]
You need to enable the ghosts feature, create a file `enable_ghosts.txt` inside the storage folder or access `https://<zoffline ip>/login/` from a browser if you are using multiplayer (in this case you must click the "Start Zwift" button to save the option, although Zwift will not actually start).

**Comment by mixenSK** [comment]
Yes, I have enable_ghosts.txt file in the storage folder 
![Snímka](https://user-images.githubusercontent.com/15002704/225387033-73953b51-ed3c-4b59-83af-6bc25e7512fc.JPG)

**Comment by oldnapalm** [comment]
To be honest I think ghosts feature in single player mode has never been properly tested on Android.

Can you try if it works with this one? Any ride longer than 300 meters should be saved as ghost.

https://github.com/oldnapalm/zwift-offline/suites/11585354625/artifacts/600363069

**Comment by oldnapalm** [comment]
I found the issue, this one should work

https://github.com/oldnapalm/zwift-offline/suites/11588417797/artifacts/600577790

**Comment by mixenSK** [comment]
Yes, it works now. Thank you very much.
