### ISSUE TITLE
What is "Multiplayer" ? How does it work?

### ISSUE THREAD

**Issue by paccW** [zoffline/zwift-offline#262]
Do I understand correctly that "Step 6 Multiplayer" enables riding online just like on the normal Zwift? 
I followed the steps but its still just offline like before.

**Comment by fatsbrown** [comment]
It allows multiple users to connect to the same zoffline server (e.g. you can ride with friends by sharing the same server instead of each one running their own server). It does NOT allow to connect to the official Zwift server.

It's also useful if you have more than one person using your server, even if not at the same time, because by default zoffline has just one profile, but if you enable multiplayer it can have multiple profiles.
