### ISSUE TITLE
 Custom workouts cannot be seen in the android app

### ISSUE THREAD

**Issue by ogperalta** [zoffline/zwift-offline#271]
I created several custom workouts and put them in the folder
C:\Users\User1\Documents\Zwift\Workouts\1 on my PC. The workouts upload correctly to the \zoffline\storage\1\customworkouts folder, however the workouts cannot be viewed from the Android app, apparently they are not downloaded to the Android client.
[New1.txt](https://github.com/zoffline/zwift-offline/files/13329470/New1.txt)

**Comment by oldnapalm** [comment]
The problem seems to be a file with the character `é` in its name.

I will look for a way to prevent this issue in the future but for now you will need to open the file `zwift-offline.db` (in storage folder) using https://sqlitebrowser.org and delete the record from the `zfile` table. Then delete the file from `storage\1\customworkouts` and rename it in `Documents\Zwift\Workouts\1`.

**Comment by ogperalta** [comment]
Thank you...I followed the instructions and now I can see the workouts on Android. thank you very much again for your support
