### ISSUE TITLE
TLS/SSL connection has been closed / Mac

### ISSUE THREAD

**Issue by Mattbln** [zoffline/zwift-offline#275]
Hi, here's the error I get when I log in: 

ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:1002)
2023-11-16T15:23:57Z <Greenlet at 0x1074ef560: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x107272c20 o)> failed with SSLZeroReturnError

I've tried all the solutions with a member of the community and we haven't managed to solve the problem. 

It's not a python problem and I didn't put the private key in the cacert.pem.

Hoping for a genius to help me out...

**Comment by peret2000** [comment]
That is, I think, the issue I have using Android as Zwift client and Linux (Raspberrypi) as zoffline server.
I haven't found any solution, as the certificate management is done by [ZofflineObb.apk](https://github.com/Argon2000/ZofflineObbAndroid/releases/latest)

**Comment by oldnapalm** [comment]
> That is, I think, the issue I have using Android as Zwift client and Linux (Raspberrypi) as zoffline server. I haven't found any solution, as the certificate management is done by [ZofflineObb.apk](https://github.com/Argon2000/ZofflineObbAndroid/releases/latest)

The certificate added by ZofflineObb is valid. Have you tried this? (from extra optional steps of readme)

change MinProtocol in /etc/ssl/openssl.cnf to TLSv1.0
  ```
  [system_default_sect]
  MinProtocol = TLSv1.0
  CipherString = DEFAULT@SECLEVEL=1
  ```

**Comment by peret2000** [comment]
Yes, I have changed the MinProtocol.
I am afraid I am confused with the certificates.

I am using [qdomyos](https://github.com/cagnulein/qdomyos-zwift) treadmill emulator. It allows to use many treadmill and bike models with Zwift, if they are not that compatible with it.
It needs to connect to zoffline server in order to ask for the slope, so that it changes treadmill inclination. It works in that way using Zwift servers. But with zoffline there are SSL handshake errors.

I guess the phone with qdomyos (a different one than the phone with zwift client) does not accept the connection to zoffline, and viceversa (zoffline logs show errors with SSL).
So I have tried to substitute cert-zwift-com.pem and key-zwift-com.pem with ones created by me, trial and error (not sure if I should put the CA certificate, or a generated server certificate, or both...).

In the end, it seems that qdomyos has connected, but now, and it seems a obvious consequence, Zwift client cannot connect.

I am struggling with the appropiate certificates deployment, but I do not get to it.

I think the best option would be to install in qdomyos phone:
- the client certificate that is validated by zoffline, if it validates it
- the CA that the phone needs to accept zoffline server certificate

But not able for the moment (I even am not sure who is who in the certs of zoffline project). I appreciate a lot your help. Several hours investigating and changing zoffline code and gevent and ssl packages, with no success.

I think qdomyos is very useful to be able to use Zwift for many treadmill models.

Thanks!

**Comment by oldnapalm** [comment]
> So I have tried to substitute cert-zwift-com.pem and key-zwift-com.pem with ones created by me

Then you need to append your cert-zwift-com.pem to `/data/data/com.zwift.zwiftgame/dataES/cacert.pem`. If your device is not rooted you can append it to https://github.com/Argon2000/ZofflineObbAndroid/blob/master/app/src/main/assets/cacert.pem and rebuild ZofflineObb.

**Comment by peret2000** [comment]
Perfect! thanks a lot for the guidance. It has been hard for me, as I had never generated an Android apk, that's the reason of the delay in the answer. But finally, I have generated my ZofflineObbAndroid version, it has worked like a charm, and, expected but not completely convinced beforehand, zoffline has worked connected to  zwift client using my own certificates.
Now, I have to solve qdomyos side, as the connection it creates with zoffline does not seem to use the certificate I would like, but that is another project's issue
Thanks!

**Comment by oldnapalm** [comment]
> Now, I have to solve qdomyos side, as the connection it creates with zoffline does not seem to use the certificate I would like, but that is another project's issue

Unfortunately I can't help with that since I don't know how it works, but one thing I can tell is that zoffline does not replicate the Zwift server authentication, it uses flask-login with a fake JWT token, so if qdomyos authenticates with the server using a second account and watch the primary account (like Sauce for Zwift) it won't work, you will need to modify it to use zoffline's login, or on a different approach, modify zoffline to expose the information you need.

**Comment by cagnulein** [comment]
> > Now, I have to solve qdomyos side, as the connection it creates with zoffline does not seem to use the certificate I would like, but that is another project's issue
> 
> Unfortunately I can't help with that since I don't know how it works, but one thing I can tell is that zoffline does not replicate the Zwift server authentication, it uses flask-login with a fake JWT token, so if qdomyos authenticates with the server using a second account and watch the primary account (like Sauce for Zwift) it won't work, you will need to modify it to use zoffline's login, or on a different approach, modify zoffline to expose the information you need.

Hi, QZ developer here, nope, QZ uses the primary Zwift account of the user. With this information, should I change something on my side to accomodate the zoffline requirements?

**Comment by oldnapalm** [comment]
> Hi, QZ developer here, nope, QZ uses the primary Zwift account of the user. With this information, should I change something on my side to accomodate the zoffline requirements?

Hi. Does it act as the Companion app (like Road Captain)? I ask because I heard from the Sauce developer that Zwift server would not allow 2 simultaneous connections from the same account.

zoffline uses 2 routes for authentication (flask-login), for Windows/Mac client (using launcher) it uses /login/ (https://github.com/zoffline/zwift-offline/blob/master/zwift_offline.py#L597) and for Android client it's done directly in /auth/realms/zwift/protocol/openid-connect/token (https://github.com/zoffline/zwift-offline/blob/master/zwift_offline.py#L3834).

**Comment by cagnulein** [comment]
> > Hi, QZ developer here, nope, QZ uses the primary Zwift account of the user. With this information, should I change something on my side to accomodate the zoffline requirements?
> 
> Hi. Does it act as the Companion app (like Road Captain)? I ask because I heard from the Sauce developer that Zwift server would not allow 2 simultaneous connections from the same account.

Yes same way. And I can confirm that I can use 2 simultaneously login without issues 

> 
> zoffline uses 2 routes for authentication (flask-login), for Windows/Mac client (using launcher) it uses /login/ (https://github.com/zoffline/zwift-offline/blob/master/zwift_offline.py#L597) and for Android client it's done directly in /auth/realms/zwift/protocol/openid-connect/token (https://github.com/zoffline/zwift-offline/blob/master/zwift_offline.py#L3834).

@peret2000 where zoffline runs on your setup?

**Comment by peret2000** [comment]
> @peret2000 where zoffline runs on your setup?

Hi. zoffline is running on linux. Specifically, in a Raspberrypi 4, with Alpine linux. Is that what you mean?
The clients are: Zwift app installed on Android phone, and QZ apk installed on another Android phone.

By the way, in case it helps, QZ is able to change treadmill inclination if, instead of being connected to zoffline, it is connected to Zwift servers.

**Comment by oldnapalm** [comment]
> Yes same way. And I can confirm that I can use 2 simultaneously login without issues

I think the difference is that Sauce simulates a Zwift client (not Companion) and gets the player states from UDP 3024, but it's unrelated to this issue.

> By the way, in case it helps, QZ is able to change treadmill inclination if, instead of being connected to zoffline, it is connected to Zwift servers.

Have you modified QZ to accept your self signed certificate?

**Comment by peret2000** [comment]
> Have you modified QZ to accept your self signed certificate?

Not really. What I did is to install a client certificate and a CA certificate in the phone, I guess that is all I can do in QZ

**Comment by peret2000** [comment]
This is the error I get from zoffline log:

`Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/.local/lib/python3.12/site-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/gevent/server.py", line 209, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/gevent/ssl.py", line 785, in wrap_socket
    return SSLSocket(sock=sock, keyfile=keyfile, certfile=certfile,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/gevent/ssl.py", line 319, in __init__
    raise x
  File "/root/.local/lib/python3.12/site-packages/gevent/ssl.py", line 315, in __init__
    self.do_handshake()
  File "/root/.local/lib/python3.12/site-packages/gevent/ssl.py", line 673, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)
2024-05-15T09:37:04Z <Greenlet at 0xe96ae118: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0xf47c3b90 ob)> failed with SSLEOFError
`

Maybe I can try to debug, in case I detect something, but not optimistic about that

**Comment by oldnapalm** [comment]
> Not really. What I did is to install a client certificate and a CA certificate in the phone, I guess that is all I can do in QZ

To get Companion working with zoffline we use apk-mitm (see step 7 of readme). Since you have access to QZ source I assumed it would no be necessary, but maybe I'm wrong.

**Comment by cagnulein** [comment]
Maybe on zoffline there is also an easy way to get the actual altitude?

**Comment by oldnapalm** [comment]
> Maybe on zoffline there is also an easy way to get the actual altitude?

Currently not, but could be easily implemented, you could add a SimpleHTTPRequestHandler in standalone.py (like https://github.com/zoffline/zwift-offline/blob/master/standalone.py#L100) which receives the player ID and returns the altitude (`online[player_id].y_altitude`).

Where does QZ get the altitude from?

**Comment by cagnulein** [comment]
@oldnapalm from the player status object in the zwift protobuf

**Comment by oldnapalm** [comment]
> @oldnapalm from the player status object in the zwift protobuf

I mean how it gets the protobuf from server. If I understood correctly from https://github.com/cagnulein/qdomyos-zwift/issues/1016#issuecomment-2105960687 it requests `/relay/worlds/<int:server_realm>/players/<int:player_id>`, this route does not require authentication in zoffline and the player_id will be 1 unless multiplayer is enabled, in which case login would be necessary to obtain the player_id from `/api/profiles/me`.

**Comment by cagnulein** [comment]
> > @oldnapalm from the player status object in the zwift protobuf
> 
> I mean how it gets the protobuf from server. If I understood correctly from [cagnulein/qdomyos-zwift#1016 (comment)](https://github.com/cagnulein/qdomyos-zwift/issues/1016#issuecomment-2105960687) it requests `/relay/worlds/<int:server_realm>/players/<int:player_id>`, this route does not require authentication in zoffline and the player_id will be 1 unless multiplayer is enabled, in which case login would be necessary to obtain the player_id from `/api/profiles/me`.

Hah Ok, I'm not aware of this @oldnapalm 
So I can skip the login thing and just try to get it. Sounds good!
I will implement this in the next days @peret2000

**Comment by peret2000** [comment]
Oh, thanks to both!. Perhaps I can help: Is it helpful if I modify my zoffline/standalone.py as @oldnapalm says in [his comment](https://github.com/zoffline/zwift-offline/issues/275#issuecomment-2112942675)? well, after @cagnulein modifies QZ to use it (or I can try to do the modifications, with some guides, hopefully).
Also, I am using multiplayer from the very beginning, as I understood it is a good feature, but perhaps it is adding complexity to the problem and it is better to avoid it?
Also, I do not know if I should test apk-mitm, I haven't understood it very well, and you say that it would not be necessary as I hava access to QZ code

**Comment by oldnapalm** [comment]
@peret2000 according to your Debug_Zwift_OFFline.log posted in https://github.com/cagnulein/qdomyos-zwift/issues/1016#issuecomment-2105954969 and following comment by @cagnulein, the problem was `https://us-or-rly101.zwift.com/relay/worlds/1/players/1126576 - server replied: Not Found`, this happened because 1126576 is probably not your player ID in zoffline, it should have requested `https://us-or-rly101.zwift.com/relay/worlds/1/players/1` (or 2, 3, etc, check the subdirectories of storage). This route does not require login in zoffline, if it worked before (without SSL errors) then you only need a way to get the correct player ID. How does QZ obtain it?

**Comment by peret2000** [comment]
If I remember correctly, when that test was done, QZ code pointed at https://us-or-rly101.zwift.com, instead of https://192.168.1.3 to get the user identification, and later, QZ used that same user id, but pointing to zoffline (using the local zoffline ip) for other requests to zwift (zoffline). So, that was a mess with the changes we were testing. I confirmed later that my user ID is 2 in zoffline.

**Comment by oldnapalm** [comment]
If you are able to connect QZ to zoffline using https://us-or-rly101.zwift.com then I guess the better way would be
- `POST https://us-or-rly101.zwift.com/login/` with `username` and `password` in request form
- `GET https://us-or-rly101.zwift.com/api/profiles/me` returns [PlayerProfile](https://github.com/zoffline/zwift-offline/blob/master/protobuf/profile.proto#L33) (or json if request header `Source` is set to `zwift-companion`) containing `id`
- `GET https://us-or-rly101.zwift.com/relay/worlds/1/players/<id>` returns [PlayerState](https://github.com/zoffline/zwift-offline/blob/master/protobuf/udp-node-msgs.proto#L112) containing `y_altitude`

**Comment by cagnulein** [comment]
thanks @oldnapalm we are trying, I will let you know how it goes. Separate question (let me know if you want to open a new discussion about this). Did you decode the protobuf about the workout session? I would like to read the actual target speed and target incline during a workout on a running session. I checked the protobuf here and I can't see these informations. Thanks

**Comment by oldnapalm** [comment]
> Did you decode the protobuf about the workout session?

No, I believe this information is not sent to the server. I think it's sent to Companion, but since it doesn't pass through the server, we have not done any investigation. Maybe you can find something in the Road Captain project, since it simulates the Companion app to make decisions at intersections and follow the planned route.

**Comment by cagnulein** [comment]
Hi @peret2000 would you like to create a zoffline PR for qz so? I saw your branch so you can contribute in this way if you want
