### ISSUE TITLE
Zwift cannot connect to internet

### ISSUE THREAD

**Issue by Reverbsz** [zoffline/zwift-offline#298]
I am planning to do normal zwift as I got free voucher. I have comment out on the hosts file and managed to download the latest zwift update.

When I login to zwift it shows my name but when it went to the next display, it asks for the username and password again.
I tried to fill in the correct zwift email and password but it kept mentioning failed to log in, no internet connection.

I am running Zwift on MacOs Monterey.

Many thanks for your help

**Comment by fatsbrown** [comment]
Try to revert the change in cacert.pem and download the latest launcher from https://www.zwift.com/download

**Comment by unrealguest** [comment]
and if you edited the hosts file, don't forget to revert that edit as well.

**Comment by daktak** [comment]
Yeah i swap back and forth just by changing the dns

**Comment by Reverbsz** [comment]
Thank you all, will give it a try this week. Sorry for the late re-ply I was away.

**Comment by fatsbrown** [comment]
> Yeah i swap back and forth just by changing the dns

Yes, usually just reverting the change in hosts is enough, but since @Reverbsz mentioned the hosts change, being able to download the update and login, I'm assuming they actually _replaced_ the cacert.pem contents with the zoffline certificate, instead of just _appending_ it, and that would cause the reported error. Reverting to the [original cacert.pem](https://cdn.zwift.com/gameassets/Zwift_Updates_Root/Zwift_1.0.124332_93535116/data/cacert.pem) should solve the problem.
