### ISSUE TITLE
Uploading activity to Garmin aloways failed

### ISSUE THREAD

**Issue by Panisins** [zoffline/zwift-offline#307]
i click setting in the launch page, and click Garmin tab, then the launch page crash
i set up my Garmin account and password in the storage/1/garmin_credentials but it can not upload as well

**Comment by fatsbrown** [comment]
Any errors in zoffline window?

Make sure you have write permission to the storage directory.

**Comment by fatsbrown** [comment]
When you click on Settings - Garmin in the launcher it probably prints some error message in zoffline window, copy and paste this message here.

**Comment by fatsbrown** [comment]
You need to post the error message in zoffline window, something like this

![2024-02-02 11_46_21-Captura_de_tela_de_2023-08-01_22-21-58 png (1878×776)](https://github.com/zoffline/zwift-offline/assets/123950591/bd9e8edb-3afd-4ecf-bdb8-05dc00d1d7e5)

In this case the problem was a garmin_credentials.bin encrypted with different key (copied from other zoffline installation).

**Comment by oldnapalm** [comment]
Please test this branch https://github.com/zoffline/zwift-offline/tree/garmin_domain

If you are in China you may need this garth configuration https://github.com/matin/garth?tab=readme-ov-file#set-domain-for-china

For this, create a file `garmin_domain.txt` in the `storage` directory containing `garmin.cn`

If you are using the Windows exe, download the artifact from https://github.com/zoffline/zwift-offline/actions/runs/7761536288

**Comment by oldnapalm** [comment]
Issue should be fixed in https://github.com/zoffline/zwift-offline/commit/759217e3d96a386ffb131cf52755d8055c10ea90

See updated instruction regarding Garmin domain in https://github.com/zoffline/zwift-offline?tab=readme-ov-file#step-5-optional-upload-activities-to-garmin-connect

For Windows exe download artifact from https://github.com/zoffline/zwift-offline/actions/runs/7814785379
