### ISSUE TITLE
Zwift encountered the following error

### ISSUE THREAD

**Issue by TimCookss** [zoffline/zwift-offline#314]
![image](https://github.com/zoffline/zwift-offline/assets/148066348/eaee8e0b-f77a-49a8-8a83-b6abc294c1bd)
![image](https://github.com/zoffline/zwift-offline/assets/148066348/ca6209ab-a485-4f9c-902f-8e92018148fd)

How to solve it?

**Comment by fatsbrown** [comment]
Looks like the TCP port 443 is already in use by another process, you need to close it, otherwise zoffline will not be able to bind to it.

You can use `resmon.exe` (listening ports) to find the process.

![2024-03-04 14_11_05-Monitor de Recursos](https://github.com/zoffline/zwift-offline/assets/123950591/bf527b9d-8013-479b-a73f-7472ffd22a10)

**Comment by TimCookss** [comment]
thanks
