### ISSUE TITLE
The events interface

### ISSUE THREAD

**Issue by jricoclq** [zoffline/zwift-offline#316]
We have established a server based on ZOFFLINE and found that the preview images on the events interface are all empty. Is there a way to retrieve this?
![6053fc319c41d314f2885dc04f172a4](https://github.com/zoffline/zwift-offline/assets/102775665/dbb214a6-6481-481c-a081-fa3a63960320)
Another thing is that there is currently a "the zwift big spin" event at zwift. Can these frames and other prizes be displayed directly in the store as merchandise for easy purchase?
![image](https://github.com/zoffline/zwift-offline/assets/102775665/c4f6efff-7050-4b94-8b48-6d1de435a6c6)

**Comment by fatsbrown** [comment]
There are no images to retrieve because those are not real events, they are auto-generated events with the sole purpose of allowing us to ride event-only routes.

If you want to set your own custom image, set `imageUrl` (https://github.com/zoffline/zwift-offline/blob/master/protobuf/events.proto#L178). For a different image for each event I guess the best way would be adding the `image` attribute in https://github.com/zoffline/zwift-offline/blob/master/data/events.txt and then setting `event.imageUrl = item['image']` (https://github.com/zoffline/zwift-offline/blob/master/zwift_offline.py#L1338).
