### ISSUE TITLE
RoboPacers

### ISSUE THREAD

**Issue by Mattinada** [zoffline/zwift-offline#332]
amazing work.

I would like to know if it is possible to create your own RoboPacers and how. Missing a few at a red pace.

Thanks

**Comment by fatsbrown** [comment]
RoboPacers are actually activity replays, like ghosts, except that they were recorded using a power simulator.

It's possible to create your own, but it requires some work (and patience).

Some important details:
- The activity must be recorded using [update frequency](https://github.com/zoffline/zwift-offline/blob/52251b3a874a3ceaa99c3bf9b04e2782d39f2877/standalone.py#L75) of 1 second (default for ghosts is 3 seconds).
- The ride must start and finish at the same place and speed, otherwise the bot won't loop smoothly.
- The profile must have a unique player ID and contain the route ID, so that when you join the bot you take the same turns at intersections.

The script [bot_editor.py](https://github.com/zoffline/zwift-offline/blob/master/scripts/bot_editor.py) can be used to modify the profile (set name, player ID and route ID) and route (cut the exceeding points to make a perfect loop).

**Comment by Mattinada** [comment]
Thank you very much!! very efficient.
I already had something in advance but having the activity recorded at 3 seconds the bot teleports ;)
We will continue testing.
regards

**Comment by oldnapalm** [comment]
If you want to create a dynamic RoboPacer (increase power on climbs and decrease on descents) you can use this

https://github.com/oldnapalm/zwift-offline/blob/master/standalone_power.py

It requires 2 ANT sticks and https://github.com/mch/python-ant

**Comment by Mattinada** [comment]
Thanks for the help,good contribution, but I can't get it to work. I get this error:

from PowerMeterTx import PowerMeterTx, NETKEY, POWER_SENSOR_ID
ModuleNotFoundError: No module named 'PowerMeterTx'

greeting

**Comment by oldnapalm** [comment]
I forgot to mention, you need to use my fork or download this file and put in your zwift-offline folder

https://github.com/oldnapalm/zwift-offline/blob/master/PowerMeterTx.py

**Comment by Mattinada** [comment]
working!!! very grateful to both of them.
greetings
