### ISSUE TITLE
Logged in but there are no roads to ride. 

### ISSUE THREAD

**Issue by pdn-ussr** [zoffline/zwift-offline#335]
![129105_error](https://github.com/zoffline/zwift-offline/assets/57845118/3ce362a3-0123-42ab-864b-4350e45e1e6f)

**Comment by fatsbrown** [comment]
Any errors in zoffline window?

**Comment by pdn-ussr** [comment]
![129105_error2](https://github.com/zoffline/zwift-offline/assets/57845118/d62173e8-f0f4-4e0e-88b3-35e364ee8b31)

Yes, there are errors.

**Comment by fatsbrown** [comment]
Looks like the problem is caused by the recently added "bookmarks" feature, it assumes the player ID is a low number (zoffline defaults to `1` for the first player and so on) but your player ID is `4413080` which causes the bookmark ID to reach the range reserved for ghosts.

You can confirm it by deleting the folder `storage\4413080\bookmarks`, this should allow you to login, but the error should return when a new bookmark is created (end of an activity).

A possible fix (untested, may require more changes) is changing line 3047 of zwift_offline.py like this
``` python
                    state.id = i + 9000000 + player_id % 100 * 1000
```

**Comment by fatsbrown** [comment]
For executable release with the proposed fix download artifact from https://github.com/fatsbrown/zwift-offline/actions/runs/9148252934
