### ISSUE TITLE
two quick notes

### ISSUE THREAD

**Issue by mesterumanele** [zoffline/zwift-offline#359]
Hello, 
after the latest update of Z (for windows) i had two small issues, both on ZCompanion android, while i was doing a workout:
1) 3 times the button 'Erg ON' disappeared from screen for about 10sec and the power dropped to zero!
2) when i had the options to change the direction, left-right-straight, the options didn't appear on the screen; only the uturn sign (and nothing happened when clicked on it) (the direction change worked with the mouse, though)

sorry... one more thing; i did update the latest apk of ZC, 361, and had this error at the finish, never seen... shows Done, all green checked, and next show Failed!?

 "Done!  Patched file: ./zc361-patched.apk

Failed!  An error occurred:

Error: EPERM: operation not permitted, rmdir 'C:\Users\pad\AppData\Local\Temp\apk-mitm-db6f005993f70a2dcf1e2f0dbaae9b4c\decode\smali\com\facebook\common'

Thank you

**Comment by fatsbrown** [comment]
Regarding 1 and 2, I don't think they are related to zoffline, because Zwift client communicates with Companion directly over your local network. It's probably a wireless network issue, you can check Zwift log to investigate, look for "Auxiliary Controller".

About the ZCA patching error, that's just a temporary folder which could not be deleted for some reason, you can navigate to `C:\Users\pad\AppData\Local\Temp` in Windows Explorer and delete `apk-mitm-db6f005993f70a2dcf1e2f0dbaae9b4c` manually.

**Comment by mesterumanele** [comment]
The change of direction prompts, were while the Comapanion was working fine, not during those 10s interruptions! (10s is an approximation!) what was strange is that any of the prompts was available on companion! When i did my previous last workout, with the previous zoofline version, all directions prompts worked correctly! I might be wrong! Ill further test tomorrow, with the latest Companion 361. Thank you

**Comment by fatsbrown** [comment]
If something changed regarding routes decision, it's probably in Zwift and/or Companion, like I said, zoffline does not intermediate the communication between Zwift and Companion.

I have no problems with route decisions using Zwift 1.73.2 and Companion 3.61.0 during normal ride (didn't test with workouts).

**Comment by mesterumanele** [comment]
Thank you for replying!
- i did install the 3.61.  i did start one workout; in the Map tab, all buttons on the bottom are empty. first is red, the others green. what i noticed, is that, for example, the button where is supposed to be the 'eye'/camera view, works though by changing views/etc correctly, but there is no 'eye' sign!
- i didn't have the time to do a full workout to see the route decision potential errors... but not having signs on buttons would make the selection a bit confusing to guess
- now, the next point is a bit unrelated (i'm trying to run Z from android client in order to avoid using the Windows installation+Companion)
- i did install zwift client to a non-rooted android. installed, all worked, my profile, drops, level i see all on the android client. so happy... but at the end, after saving and exiting, the workout was not uploaded to garmin (as i have it, and works, with the windows zofline installation) the client android cannot upload to garmin? is something i'm missing or should add/modify in order to upload to Garmin from android client? or i have to upload the fit file manually to garmin?
Thank you

**Comment by fatsbrown** [comment]
When running Companion you can't redirect `cdn.zwift.com` to zoffline, otherwise it won't be able to download images (like the buttons) from the official server.

About Android Zwift not uploading to Garmin, I have no idea, I would look for errors in zoffline and also in Zwift log (https://support.zwift.com/locating-log-files-BykKO63fr#Android). In theory it should work the same as Windows, since the Garmin credentials are stored on zoffline and not on Zwift client.

**Comment by mesterumanele** [comment]
Thank you again!
i understand... 
- when running companion i load the host with 2 lines, when i run the android client i load the host with 3 lines; this solves the issue with the buttons. great!
- from android client, the loading to garmin worked after i made a test workout of 3min+... maybe yesterday the loading didn't work because the workout was under 3min? great!
Thank you

**Comment by fatsbrown** [comment]
The activity won't be saved if shorter than 300 meters.
