### ISSUE TITLE
MacOS is unable to update the Zwift app

### ISSUE THREAD

**Issue by qinlonghao** [zoffline/zwift-offline#370]
The version is 135674.
After opening zwiftoffline, the update shows' broken pipe 'in Python.
After deleting hosts, update directly and display "An SSL error has occurred and a secure connection to the server cannot be made."

**Comment by fatsbrown** [comment]
This may be due to 135674 still being is phased rollout (http://cdn.zwift.com/gameassets/Zwift_Updates_Root/ZwiftMac_ver_cur.xml is still 135346 and the launcher may redirect you to http://cdn.zwift.com/gameassets/Zwift_Updates_Root/ZwiftMac_ver_cur.135674.xml or not).

When the phased rollout is over (should be shortly), once you remove the line from hosts you should be updated to definitive 135674 from official server, then the latest zoffline should work after re-adding the line to hosts. If it still doesn't work, post the full error messages from zoffline log.
