### ISSUE TITLE
Type error,server cannot run

### ISSUE THREAD

**Issue by captainjzj** [zoffline/zwift-offline#375]
Finish step 1&2 on mac
Try to run standalone.py, it shows the errors
Cannot inherit frozen dataclasss from a non frozen one
![image](https://github.com/user-attachments/assets/ecd3e64e-3de3-42cf-9594-a5fd82f26205)

**Comment by fatsbrown** [comment]
Looks like a pint (stravalib dependency) issue with Python 3.13 https://github.com/hgrecco/pint/issues/1969

I suggest downgrading to Python 3.12 until the issue is resolved. Another option is using Docker.

**Comment by fatsbrown** [comment]
Looks like a pint (stravalib dependency) issue with Python 3.13 https://github.com/hgrecco/pint/issues/1969

I suggest downgrading to Python 3.12 until the issue is resolved. Another option is using Docker.

If you don't need Strava upload you can simply delete these lines

https://github.com/zoffline/zwift-offline/blob/75de4a98c965922d5d596c645f1243849e8b7b08/zwift_offline.py#L135C1-L137C40

**Comment by fatsbrown** [comment]
Pint was updated, it's working with Python 3.13 now.
