### ISSUE TITLE
Zoffline server issue

### ISSUE THREAD

**Issue by zwoffline** [zoffline/zwift-offline#377]
Hello,

I think i followed all steps to create a server on my windows PC with multiplayer.txt, then create a modified app and hosts file on my android device. I opened TCP and UDP ports in my router and windows firewall. But whenever i try to connect to the IP address of my PC running de server the android app with the correct hosts.txt activated doesn't connect. I've  used IPv4 version of my IP but it doesn't connect. I can only connect when using the Android app under the same network and using local ip address on hosts

Does anyone have any experience setting up a remote server for group rides (meetups) ?

**Comment by fatsbrown** [comment]
When you tried to connect using the public IP, was it from inside the local network or from the internet?

Usually, to be able to connect through the public IP from the local network, you need to configure [NAT hairpinning](https://en.wikipedia.org/wiki/Network_address_translation#NAT_hairpinning) in the router.

Also notice that you must set the public IP in server-ip.txt, otherwise the players won't be able to see each other.
