### ISSUE TITLE
Zwift client on iPad

### ISSUE THREAD

**Issue by mazafra1** [zoffline/zwift-offline#399]
I've tried to make this work using an iPad as Zwift client unsuccessfully. I know this is not supported yet, but I'd like to contribute here and make some tests myself.

Although zoffline is working properly on a macOS when I run the Zwift client within it. 

**SETUP** 
I switched the client to the iPad performing at the same time the following changes:
1. I installed [Squid](http://www.squid-cache.org) on the Mac to serve as proxy server.
2. Create a hosts file for Squid containing: 
```
127.0.0.1 us-or-rly101.zwift.com
127.0.0.1 secure.zwift.com
127.0.0.1 cdn.zwift.com
127.0.0.1 launcher.zwift.com
```
3. In the `squid.conf` file I included:
```
hosts_file /usr/local/squid/etc/squid_hosts
acl localnet src 192.168.0.0/16
http_access allow localnet
http_access allow all
```
4. I created the `server-ip.txt` containing the macOS's (zoffline server) IP.
5. Set up the `<macOS_ip>:3128` as default proxy server on the iPad.
6. I installed the pen certificate on the iPad
7. Run the Zwift app on the iPad

**PROBLEM**
Zwift client is running normally (like no zoffline is there). It seems the iPad app does not even try to connect to the proxy (Squid logs don't show any attempt).

Any idea?

**Comment by fatsbrown** [comment]
I have never tried on iOS but can confirm that on Android the Zwift app ignores proxy settings.

You can try the "fake DNS" method mentioned in the non-rooted Android instructions

> create a ``fake-dns.txt`` file in the ``storage`` directory and set the "DNS 1" of your phone Wi-Fi connection to the IP address of the PC running zoffline

You will still have the (bigger) issue of making Zwift trust the zoffline SSL certificate (append it to cacert.pem), I believe it requires a jailbroken device.

https://github.com/v4mp1/zwift-offline/tree/work-dir?tab=readme-ov-file#client-install

**Comment by oldnapalm** [comment]
Adding support for iPhone/iPad is not planned. If you manage to get it working and want to contribute with instructions, please don't include jailbreak instructions, because it changes frequently and will be outdated in no time.

Example:

* Create a ``fake-dns.txt`` file in the ``storage`` directory and set the DNS server of your device Wi-Fi to the IP address of the PC running zoffline.
* Jailbreak your device.
* Append the certificate from [cert-zwift-com.pem](https://github.com/zoffline/zwift-offline/raw/master/ssl/cert-zwift-com.pem) to `/var/containers/Bundle/Application/Zwift/Zwift.app/dataES/cacert.pem` (only the certificate, not the private key).
