### ISSUE TITLE
URL: Auth Strava not work

### ISSUE THREAD

**Issue by josepdomotica** [zoffline/zwift-offline#400]
I'm trying to go through the Strava authentication step to automate activity uploads but it seems that Zwift has changed the link, it's not a valid 'launcher.zwift.com'.

I've tried both with the .exe and directly in the 'settings' within the launcher.

Thanks

**Comment by fatsbrown** [comment]
It does not depend on Zwift. It will only work through the launcher settings if you set the authorization callback domain of your API application to `launcher.zwift.com` (as mentioned in README). If you use the `strava_auth` script it should work regardless of the application authorization callback domain, because it uses `localhost`.

**Comment by josepdomotica** [comment]
Yes, I noticed and that's why I closed the case. I have already validated and authorized it, I just completed a 2-minute zoffline test and at the end of the training I got Strava (in color, so everything seemed OK), but the activity didn't actually upload to Strava.

**Comment by fatsbrown** [comment]
Notice the activity must be at least 300 meters, otherwise it won't be saved. If it was, but still was not uploaded, check the zoffline window for errors.
