### ISSUE TITLE
zwift launcher not working

### ISSUE THREAD

**Issue by Stonekity** [zoffline/zwift-offline#404]
Platform : windows
Zoffline: zoffline_1.0.136993.exe & zoffline_1.0.137546.exe （I have tested both versions, and basically both have the following problems）
Zwift:  lastest version

I have been unable to successfully install the Windows version of zoffline today and encountered several abnormal problems:

1. After the first installation of zwift, I turned on offline mode and started zwift launcher. It triggered the update again and it would be stuck all the time. I needed to turn on the VPN network to complete the update.

<img width="999" alt="image" src="https://github.com/user-attachments/assets/5c54c935-e1d9-4363-842d-9b9bc689200b" />

2. After the update was completed, sometimes I couldn't start Zwift by clicking the Start Zwift button. It would always show "Loading zwift"

<img width="1147" alt="image" src="https://github.com/user-attachments/assets/e0a804a3-67c4-4b6e-8f7c-15c6324a9ed7" />

3. After restarting Zwift, I found that I could no longer enter Zwift Launcher. Every time I opened it, I went directly to the Zwift page, and I had to enter the correct zwift account and password to log in.

**Comment by fatsbrown** [comment]
This usually happens when Zwift is updated from the official server during the "phased rollout" period. During this period, the file `Zwift_ver_cur_filename.txt` in Zwift folder contains the version number (e.g. `Zwift_ver_cur.137546.xml` instead of just `Zwift_ver_cur.xml`).

It's recommend to wait until the phased rollout is complete before updating (as mentioned in #343, zoffline is able to proxy the update files in many cases, but it's not guaranteed that it will work).

- Run `disable_zoffline.bat` (or disable zoffline according to https://github.com/zoffline/zwift-offline?tab=readme-ov-file#enablingdisabling-zoffline)
- Confirm that http://cdn.zwift.com/gameassets/Zwift_Updates_Root/Zwift_ver_cur.xml is already the updated version (same as http://cdn.zwift.com/gameassets/Zwift_Updates_Root/Zwift_ver_cur.137546.xml as of yesterday)
- If it's already the new version, it means the phased rollout is complete, then you can run Zwift and it will be updated in the "definitive" format
- Run `configure_client.bat` (or enable zoffline according to https://github.com/zoffline/zwift-offline?tab=readme-ov-file#enablingdisabling-zoffline)
- Update zoffline and run Zwift

**Comment by Stonekity** [comment]
Does it mean that I encountered the Zwift server update maintenance period when I installed it? If I install it at night (UTC+8 time zone), I will not encounter this problem? There is another question that confuses me. Do you mean that if I install it during the Zwift server update maintenance period, the Zwift client will pull down Zwift_ver_cur.137546.xml instead of Zwift_ver_cur.xml?

**Comment by fatsbrown** [comment]
> Does it mean that I encountered the Zwift server update maintenance period when I installed it?

It's not "maintenance", they always use this "phases rollout" for updates, meaning not all users receive the update at the same time. It usually takes 2 days to complete.

> If I install it at night (UTC+8 time zone), I will not encounter this problem?

No, because it usually takes 2 days to complete, as mentioned above. The only way to be sure is checking the Zwift_ver_cur.xml file from the official server (second item in my previous comment) or checking the forum
- start https://forums.zwift.com/t/game-update-v-1-80-december-2024/640742
- finish https://forums.zwift.com/t/game-update-v-1-80-december-2024/640742/51

> After I installed the Zwift client and started downloading and updating, I was able to log into the game by logging into the official Zwift account. However, after starting zoffline and configuring hosts, the update download was still triggered. Is this because the file pulled down from my Zwift installation directory is not Zwift_ver_cur.xml, but Zwift_ver_cur.137546.xml? I noticed yesterday that when this abnormal situation occurred, there was indeed only Zwift_ver_cur.137546.xml in the Zwift installation directory, and no Zwift_ver_cur.xml

Yes, it seems to be the reason.

**Comment by Stonekity** [comment]
> A possible workaround for this situation (I have not tested it but I believe it should work) is renaming the file `Zwift_ver_cur.137546.xml` in the Zwift directory to `Zwift_ver_cur.xml` and editing the file `Zwift_ver_cur_filename.txt` content to match it (delete `.137546`).

Okay, thank you for your help, buddy. I'll give it a try and thank you very much for your reply.

**Comment by fatsbrown** [comment]
Did you use the workaround or it was already working?

If the workaround is confirmed I can suggest a note in the README.

**Comment by Stonekity** [comment]
> Did you use the workaround or it was already working?
> 
> If the workaround is confirmed I can suggest a note in the README.

Now it's normal, I don't have the opportunity to test the previous abnormal situation. If I encounter it again, I will test it as soon as possible and the results will be synchronized here. thank you

**Comment by Stonekity** [comment]
> Did you use the workaround or it was already working?
> 
> If the workaround is confirmed I can suggest a note in the README.

Brother, I encountered this problem again when I installed the Windows version today. Then I tested this solution and found that it did not solve the problem. It still triggered the download update and caused failure.

<img width="483" alt="image" src="https://github.com/user-attachments/assets/cc7d7181-2b96-44e6-bd0d-a2340c3245c9" />

<img width="495" alt="image" src="https://github.com/user-attachments/assets/ec6f31dc-6630-4506-a045-949afa8e6ef3" />

<img width="899" alt="image" src="https://github.com/user-attachments/assets/d21d8811-16bf-45cd-bb62-0b414c4a4154" />

<img width="901" alt="image" src="https://github.com/user-attachments/assets/caa89ea7-155e-4872-9134-cbe4f2f43ad2" />

<img width="898" alt="image" src="https://github.com/user-attachments/assets/a589849d-8971-41cc-ac27-926685b558f4" />

**Comment by fatsbrown** [comment]
The problem is that you are still using `zoffline_1.0.137546.exe`, you have to download `zoffline_1.0.138664.exe` from https://github.com/zoffline/zwift-offline/releases/tag/zoffline_1.0.138664

Make sure you also edit `Zwift_ver_cur_filename.txt` and delete `.138664`.
