### ISSUE TITLE
Better Ghost rider start_lines.csv documentation

### ISSUE THREAD

**Issue by rdvAndroid** [zoffline/zwift-offline#97]
I've successfully recorded multiple >5km routes using Zoffline and can see the ghost bin files but a re-ride of that same route, with Ghost enabled, has never had the ghost rider showing up.
The "start_lines.csv" is not documented well enough to understand what needs to be alter when the ghost rider starts. For instance I see "roadTime" but are the values milliseconds or some other number? If so where can I get or calculate those numbers.
Columns "course" and "spawnRoad" match the directory structure and I can guess that "isForward" needs to match the direction the ghost bin file was riding when recorded but that is just a guess. I've no idea where "startRoad" value can be obtained.

It would help a lot if there was a better explanation of what the columns mean, where to get that information if not just part of the directory structure and an example of how to alter the csv file to get a Ghost rider to appear when and where you want.

Outside of Ghost riders never showing up Zoffline is working without a hitch.

Thank you for your work

**Comment by oldnapalm** [comment]
Hi @rdvAndroid

The file start_lines.csv should not need to be modified unless you want to enable optional start lines (e.g. if you want the ghosts to spawn at Alpe du Zwift segment start).
* To enable "Road to Sky" or "Jungle Circuit", move it above "Jungle start pens".
* To enable "Ven-Top", move it above "France".

The feature is enabled in the launcher window (Windows and macOS). If you are running Zwift on Android, you will need to create a file "enable_ghosts.txt" inside the storage folder (just added it to the instructions).

The meaning of the columns in start_lines.csv is a bit hard to explain, please take a look in https://github.com/zoffline/zwift-offline/issues/56

**Comment by oldnapalm** [comment]
Sorry, if you have ghosts saved, the feature must be enabled. Are you selecting "surprise me" in route? If that's the case, then you really need to edit start_lines.csv (I didn't check all maps, but for some the start location is different if you choose "surprise me" instead of selecting a route). You can either delete the lines for that map (then the ghosts will start right away) or change the data. Add this line before https://github.com/zoffline/zwift-offline/blob/b4f2aff503502ff375c1aa3bff1caeb9e1f90143/standalone.py#L319

`            else: print('course', course(recv.state), 'road', roadID(recv.state), 'isForward', isForward(recv.state), 'roadTime', recv.state.roadTime)`

then when you stop you will see the data in terminal, e.g.

`course 6 road 81 isForward True roadTime 930423`

**Comment by rdvAndroid** [comment]
Some good news. As I was using the Win10 Zoffline executable it was easiest for me to test the ghost rider functionality by removing the map's row in start_lines.csv just to prove my install and route recordings were functional. The good news is the ghost started immediately as if shot out of a cannon. 

I'll now try to figure out the rest using your other suggestions. Before you ask I saw your other commits that were related to Ghost riders.

Thanks for your quick response to my request.
